project:
  type: website
  render:
    - "*.qmd"
    - "posts/*.md"
    - "posts/*.ipynb"
  resources:
    - "assets/"

website:
  description: "Albert's personal technical blog"
  site-url: https://Git-AIbert.github.io
  title: "Albert's Notes"
  favicon: assets/favicon.svg
  navbar: true
  comments:
    utterances:
      repo: Git-AIbert/Git-AIbert.github.io

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    highlight-style: github
